# LFX260 Page 76

version: "3.3"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=US/Central
    volumes:
      - nextcloud-config:/config
      - nextcloud-data:/data
    ports:
      - 443:443
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - GUID=1000
      - MYSQL_ROOT_PASSWORD=ChangeMePlease
      - TZ=US/Central
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=ChangeMeAlso
    #ports:
    #  - 3306:3306
    volumes:
      - mariadb-config:/config
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3 

volumes:
  nextcloud-config:
    driver: local
  nextcloud-data:
    driver: local
  mariadb-config:
    driver: local
