# Commands:
#    docker-compose build
#    docker tag crash_test:latest registry-host:5000/crash_test:latest
#    docker push registry-host:5000/crash_test:latest
#    docker stack deploy crash -c docker-compose.yaml
#    docker service scale crash_test=2
#    docker service update crash_test   <-- Restart if on-failure max-attempts reached

version: '3'

services:
    test:
      build: .
      image: registry-host:5000/crash_test:latest
      deploy:
        restart_policy:
          #condition: none
          #condition: any   # Default
          condition: on-failure
          max_attempts: 3 
