name: grafana
services:
    grafana:
        container_name: grafana
        restart: always
        ports:
            - 0.0.0.0:3000:3000
        env_file:
            - /root/configs/env-file-grafana
        environment:
            - GF_RENDERING_RENDERER_TOKEN=hello
            - GF_RENDERING_SERVER_URL=http://192.168.7.140:8085/render
            - GF_RENDERING_CALLBACK_URL=http://192.168.7.140:3000/
            - GF_LOG_FILTERS=rendering:debug 
        volumes:
            - grafana:/var/lib/grafana
        image: docker.io/grafana/grafana:9.5.21-ubuntu
    renderer:
        container_name: grafana-image-renderer
        restart: always
        ports:
            - 0.0.0.0:8085:8081
        environment:
            - AUTH_TOKEN=hello
        image: docker.io/grafana/grafana-image-renderer:3.12.4
volumes:
    grafana:
        external: true
        name: grafana
