version: '3'
services:
    redis:
        container_name: example1_redis
        image: redis:5-alpine
        volumes:
            - ./redis:/data
        restart: always
    mariadb:
        container_name: example1_mysql
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
