# Source: https://github.com/crowdsecurity/cs-nginx-blocker#installation
# Source: https://github.com/crowdsecurity/crowdsec
FROM nginx:1.19.3

WORKDIR /opt/

ARG DEBIAN_FRONTEND=noninteractive
#ENV TZ=America/Chicago
RUN apt-get update && apt-get install -y bash gettext whiptail curl wget procps

RUN curl -s https://api.github.com/repos/crowdsecurity/crowdsec/releases/latest | grep browser_download_url| cut -d '"' -f 4  | wget -i -
RUN tar xvfz crowdsec-release.tgz
RUN cd crowdsec-v*

