advanced:
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://10.88.0.1:1883
serial:
  adapter: deconz
  port: /dev/ttyACM0
  baudrate: 115200
frontend:
  enabled: true
devices:
  '0x0022a300003d42bd':
    friendly_name: FrontOutsideLights
version: 4
