# Source: https://github.com/polinchw/rancher-docker-compose/blob/master/docker-compose.yaml

version: '3.3'

services:
  app:
    image: rancher/rancher:latest
    ports:
      - "8443:443/tcp"
    volumes:
      - "data:/var/lib/rancher"
    environment:
      - VIRTUAL_HOST=rancher.local
    deploy:  # Settings for Swarm mode
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5

volumes:
  data:
    driver: local

# docker network create -d overlay internal_network
networks:
  default:
    external:
      name: swarm_default

